### ISSUE TITLE
error: cannot run ssh: No such file or directory

### ISSUE THREAD

**Issue by stephenlawrence** [Cimpress-MCP/docker-git2consul#1]
When I run git2consul container it injects the configs and then dies here. Is ssh or git a requirement and it is missing?

git2consul | {"name":"git2consul","hostname":"37da0188e780","pid":1,"level":10,"msg":"Adding key com.company/company-configurations-bitbucket/docker.ref, value:\nnull","time":"2016-04-01T22:22:31.473Z","v":0}

git2consul | {"name":"git2consul","hostname":"37da0188e780","pid":1,"level":10,"msg":"Running git clone -b docker ssh://git@bitbucket.company.io:7999/~username/company-environment.git docker in /tmp/company-configurations-bitbucket","time":"2016-04-01T22:22:31.493Z","v":0}

git2consul | {"name":"git2consul","hostname":"37da0188e780","pid":1,"level":10,"msg":"stderr:\nCloning into 'docker'...\nerror: cannot run ssh: No such file or directory\nfatal: unable to fork","time":"2016-04-01T22:22:31.532Z","v":0}

git2consul | {"name":"git2consul","hostname":"37da0188e780","pid":1,"level":50,"msg":"Failed to create repos due to Failed to load repo company-configurations-bitbucket due to Error: Error: Command failed: /bin/sh -c git clone -b docker ssh://git@bitbucket.company.io:7999/~username/company-environment.git docker\nCloning into 'docker'...\nerror: cannot run ssh: No such file or directory\nfatal: unable to fork\n Cloning into 'docker'...\nerror: cannot run ssh: No such file or directory\nfatal: unable to fork","time":"2016-04-01T22:22:31.539Z","v":0}

**Comment by calvn** [comment]
It is indeed because there is no ssh for the image. I will upload a new release shortly. Thanks for the report!

**Comment by calvn** [comment]
The latest image should have openssh installed.

**Comment by stephenlawrence** [comment]
lgtm
