### ISSUE TITLE
How do we use the SSH keys for our git host?

### ISSUE THREAD

**Issue by stephenlawrence** [Cimpress-MCP/docker-git2consul#2]
If I need to created ssh keys for bitbucket, how would I pass-in that key to the git2consul container so that it can connect to an ssh endpoint?

**Comment by calvn** [comment]
Have you tried mounting a volume that contains the SSH key to the container?

**Comment by stephenlawrence** [comment]
I ended up copying an id_rsa and known_hosts files into /root/.ssh/ during the Dockerfile build and then adding that key to the bitbuck access key setting.

**Comment by calvn** [comment]
Closing this since you found a proper workaround,

**Comment by spanktar** [comment]
Where would one mount this to allow it to be picked up by the local git call?
Do we need to also set the GIT_SSH_COMMAND?

I tried this to no avail:

```
docker run \
  --name git2consul \
  -e GIT_SSH_COMMAND="ssh -i /root/.ssh/id_ecdsa" \
  -v /home/foo/.ssh:/root/.ssh \
  -v /etc/git2consul.d:/etc/git2consul.d \
cimpress/git2consul:deploy \
  --endpoint 10.0.90.46 \
  --port 8500 \
  --config-file /etc/git2consul.d/config.json
```

After this I tried a bunch of other things short of baking my keys into my own image and nothing worked.  It would be great to have a built-in way to handle this.  I gave up on the container (for now) and went to the NPM version which works great.

**Comment by swyrik** [comment]
> I ended up copying an id_rsa and known_hosts files into /root/.ssh/ during the Dockerfile build and then adding that key to the bitbuck access key setting.

can you please explain in brief how you have done that.
